try {
    console.log(naoExisto)
} catch (error) {
    console.log('Erro, vari√°vel inexistente');
}